package com.ssafy.domain.company.entity;

public enum AssetType {

    CURRENT_ASSETS,
    NON_CURRENT_ASSETS,
    TOTAL_ASSETS,
    CURRENT_LIABILITIES,
    NON_CURRENT_LIABILITIES,
    TOTAL_LIABILITIES,
    CAPITAL_STOCK,
    ADDITIONAL_PAID_IN_CAPITAL,
    RETAINED_EARNINGS,
    CAPITAL_ADJUSTMENTS,
    TOTAL_EQUITY,
    SALES_REVENUE,
    GROSS_PROFIT,
    OPERATING_INCOME,
    NON_OPERATING_INCOME,
    NON_OPERATING_EXPENSES,
    NET_INCOME,
    STATEMENT_OF_CASH_FLOWS,
    CASH_FLOWS_FROM_OPERATING_ACTIVITIES,
    CASH_FLOWS_FROM_INVESTING_ACTIVITIES,
    CASH_FLOWS_FROM_FINANCING_ACTIVITIES,
    NET_INCREASE_DECREASE_IN_CASH,
    CASH_AT_END_OF_PERIOD,

}
